OpenQA Stability Analysis Tool
QubesOS/openqa-tests-qubesos pull request #14
Opened 2021-11-04 09:13 UTC by deeplow

Adds the util for analyzing the stability of tests. It analyses historical test data from openqa.qubes-os.org outputs results in several formats:
  - markdown table report
  - markdown reports of all the matching results
  - plot of errors (last two traceback lines)
  - plot of templates
  - plot of failures by test title

### Configuration parameters
  - **test suite** (e.g. `--suite system_tests_splitgpg`)
  - **test name** - (e.g. --test "VmIPv6Networking_fedora-34/test_.*"
  - **error regex** - if you're looking for an error of a particular type (e.g. `--error ".*dogtail.*"`)
  - **approx. history length** - how far you want to go in historical data (e.g. `--last 20`)
  - **openqa job group** -  currently hardcoded to ["pull requests"](https://openqa.qubes-os.org/group_overview/11)

### Example plot

![](https://user-images.githubusercontent.com/47065258/136524366-01c39d19-4eaa-4bc9-b7b7-95ab31178618.png)

### Future work
Future work will be integrating this with `github_reporting.py` such that it produces useful information on new errors.

2021-11-04 09:15 UTC, deeplow commented
Let me know if all requirements (imports) are ok.

2021-11-13 03:49 UTC, marmarek commented
> Let me know if all requirements (imports) are ok.

All seems to be packaged in Fedora at least, so that's ok.

2021-11-13 03:53 UTC, marmarek requested changes

2021-11-13 03:53 UTC, marmarek commented on utils/openqa_investigator.py
> +    plot_simple(title, jobs, test_suite, group_by_template, outfile)
This looks like a rebase error. `group_by_template` is defined twice, and `plot_simple` is also called twice.

2021-11-22 22:06 UTC, marmarek approved these changes

2021-11-29 04:55 UTC, merged